-- Task stages are now created automatically when:
-- 1. A new user registers (personal stages with user_id)
-- 2. A new team is created (team stages with team_id)
-- This file is kept for reference but no longer seeds global stages