apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      imagePullSecrets:
        - name: registry-1
      containers:
        - env:
            {{- range $key, $value := index .Values "api" "env" }}
              {{- if kindIs "map" $value }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $value.secretKeyRef.name }}
                    key: {{ $value.secretKeyRef.key }}
              {{- else }}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}
              {{- end }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          name: api
#          resources:
#            limits:
#              cpu: 200m
#              memory: 256Mi
#            requests:
#              cpu: 200m
#              memory: 128Mi
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always